"""restructure stat_entry fields: drop calories/heart_rate/travel, add injuries

Revision ID: 74fb98d0a2f0
Revises: 4a5e45838c51
Create Date: 2026-07-02 15:37:55.463263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fb98d0a2f0'
down_revision = '4a5e45838c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injuries', sa.Integer(), nullable=True))
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('calories')
        batch_op.drop_column('travel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate', sa.INTEGER(), nullable=True))
        batch_op.drop_column('injuries')

    # ### end Alembic commands ###
